name: Deploy source changes

on:  
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Trigger server update
        run: curl -X GET https://spooder.dev/internal/update?key=${{ secrets.SPOODER_UPDATE_KEY }}